In [13]:
# # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import sys
# Import API key
from api_keys import api_key
from api_keys2 import api_key2

## read 10,000 Movie ID from 2009 ~ 2019 through TMDB API URL

In [2]:
record_counter = 0
movie_id_list = []
base_url= "https://api.themoviedb.org/3/discover/movie?"

print("Beginning Data Retrieval\n")
print("-"*30)

for page in range(500):   
    movie_url=base_url+"primary_release_date.gte=2009-01-01&primary_release_date.lte=2019-10-23&api_key="+api_key+"&page="+str(page+1)
    response=requests.get(movie_url).json()
    for index in range(len(response['results'])):
        movie_id_list.append(response['results'][index]["id"])
        record_counter+=1
        sys.stdout.write('\r'+'Processing Record '+str(record_counter))
        sys.stdout.flush()

print ("\nData Retrieval Complete\n")
print ("-"*30)
print ("Movie Found "+str(record_counter))
print(f"There are {len(movie_id_list)} in the List")

Beginning Data Retrieval

------------------------------
Processing Record 10000
Data Retrieval Complete

------------------------------
Movie Found 10000
There are 10000 in the List

## scrap 10,000 records year 2009 to 2019 from TMDB API by ID

In [4]:
#initial counter
record_counter=0
set_counter=1

#define list
id_list=[]
title_list=[]
adult_list=[]
budget_list=[]
genres_list=[]
language_list=[]
pop_list=[]
company_list=[]
country_list=[]
release_date_list=[]
revenue_list=[]
run_time_list=[]
vote_ave_list=[]
vote_count_list=[]
imdb_id_list=[]

base_url = "https://api.themoviedb.org/3/movie/"

print("Beginning Data Retrieval\n")
print("-"*30)
#Scrap data from api
for m_id in movie_id_list:
    try:
        url=base_url+str(m_id)+"?api_key="+api_key#+"&language=en-US"
        response=requests.get(url).json()
        id_list.append(response["id"])
        title_list.append(response["title"])
        adult_list.append(response["adult"])
        budget_list.append(response["budget"])
        genres_list.append([i["name"] for i in response["genres"]])
        language_list.append(response["original_language"])
        pop_list.append(response["popularity"])
        company_list.append([j["name"] for j in response["production_companies"]])
        country_list.append([k["name"] for k in response["production_countries"]])
        release_date_list.append(response["release_date"])
        revenue_list.append(response["revenue"])
        run_time_list.append(response["runtime"])
        vote_ave_list.append(response["vote_average"])
        vote_count_list.append(response["vote_count"])
        imdb_id_list.append(response["imdb_id"])
        
        record_counter+=1
        sys.stdout.write('\r'+'Processing Record '+str(record_counter))
        sys.stdout.flush()

    except:
        pass

print ("\nData Retrieval Complete\n")
print ("-"*30)
print ("Movie Found "+str(record_counter))

Beginning Data Retrieval

------------------------------
Processing Record 9994
Data Retrieval Complete

------------------------------
Movie Found 9994

### DataFram of tmdb_movie_df

In [18]:
tmdb_movie_df=pd.DataFrame({"ID":id_list,
                       "Title": title_list,
                       "Adult":adult_list,
                       "Budget":budget_list,
                       "Genres":genres_list,
                       "Language":language_list,
                       "Production Company":company_list,
                       "Popularity":pop_list,
                       "Revenue":revenue_list,
                       "Production Country":country_list,
                       "Release Date":release_date_list,
                       "Run Time":run_time_list,
                       "Vote Average":vote_ave_list,
                       "Vote Count":vote_count_list,
                       "imdb_id": imdb_id_list})
tmdb_movie_df.head()

,ID,Title,Adult,Budget,Genres,Language,Production Company,Popularity,Revenue,Production Country,Release Date,Run Time,Vote Average,Vote Count,imdb_id
0,475557,Joker,False,55000000,"[Crime, Thriller, Drama]",en,"[DC Entertainment, Warner Bros. Pictures, DC C...",462.910,568509478,[United States of America],2019-10-02,122.0,8.6,3863,tt7286456
1,420809,Maleficent: Mistress of Evil,False,0,"[Fantasy, Adventure, Family]",en,[Walt Disney Pictures],287.919,0,[United States of America],2019-10-16,118.0,7.1,317,tt4777008
2,420818,The Lion King,False,260000000,"[Adventure, Animation, Drama]",en,"[Walt Disney Pictures, Fairview Entertainment]",183.255,1649676757,[United States of America],2019-07-12,118.0,7.1,3132,tt6105098
3,290859,Terminator: Dark Fate,False,160000000,"[Action, Science Fiction]",en,"[Lightstorm Entertainment, Skydance Media, 20t...",153.313,0,"[China, United States of America]",2019-10-23,128.0,7.4,29,tt6450804
4,429617,Spider-Man: Far from Home,False,160000000,"[Action, Adventure, Science Fiction]",en,"[Marvel Studios, Sony Pictures, Columbia Pictu...",123.576,1131450163,[United States of America],2019-06-28,129.0,7.6,4610,tt6320628

In [7]:
#save data frame to csv
movie_df.to_csv("output_data/tmd_api_movie_2019.csv",index=False)