## General Clean Up Data and Save to CSV file
##### Drop columns with the same data info and convert the 0 values in Budget and Revenue Section to Null, in order to finalize the final Data frame for analyzing

In [1]:
# # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import sys
# Import API key
# from api_keys import api_key
# from api_keys2 import api_key2

#### Merge OMDB & TMDB From Excel files

In [2]:
# Recall the OMDB data and TMDB data
df_tmdb = pd.read_csv("output_data/tmd_api_movie_2019.csv")
df_omdb = pd.read_csv("output_data/omdb_api_movie_2019.csv")

In [3]:
#combine the OMDB and TMDB data to generate final dataframe
df_tmdb["omdb_id"] = df_tmdb["imdb_id"]
df_imdb = pd.merge(df_tmdb, df_omdb, on="omdb_id", how="left")
df_imdb.head()

,ID,Title,Adult,Budget,Genres,Language,Production Company,Popularity,Revenue,Production Country,...,omdb_released,omdb_runtime,omdb_director,omdb_actors,omdb_language,omdb_country,omdb_ratings,omdb_metascore,omdb_imdbRating,omdb_imdbVotes
0,475557,Joker,False,55000000,"['Crime', 'Thriller', 'Drama']",en,"['DC Entertainment', 'Warner Bros. Pictures', ...",601.364,788300000,['United States of America'],...,04 Oct 2019,122 min,Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",English,"USA, Canada","[{'Source': 'Internet Movie Database', 'Value'...",59.0,8.9,"360,218"
1,420809,Maleficent: Mistress of Evil,False,0,"['Fantasy', 'Adventure', 'Family']",en,['Walt Disney Pictures'],257.685,0,['United States of America'],...,18 Oct 2019,118 min,Joachim Rønning,"Angelina Jolie, Elle Fanning, Imelda Staunton,...",English,USA,"[{'Source': 'Rotten Tomatoes', 'Value': '51%'}]",NaN,NaN,NaN
2,290859,Terminator: Dark Fate,False,160000000,"['Action', 'Science Fiction']",en,"['Lightstorm Entertainment', 'Skydance Media',...",223.592,0,"['China', 'United States of America']",...,01 Nov 2019,NaN,Tim Miller,"Linda Hamilton, Arnold Schwarzenegger, Mackenz...",English,"China, USA",[],NaN,NaN,NaN
3,420818,The Lion King,False,260000000,"['Adventure', 'Animation', 'Drama']",en,"['Walt Disney Pictures', 'Fairview Entertainme...",180.573,1649676757,['United States of America'],...,19 Jul 2019,118 min,Jon Favreau,"Chiwetel Ejiofor, John Oliver, James Earl Jone...",English,USA,"[{'Source': 'Internet Movie Database', 'Value'...",55.0,7.1,"102,621"
4,429617,Spider-Man: Far from Home,False,160000000,"['Action', 'Adventure', 'Science Fiction']",en,"['Marvel Studios', 'Sony Pictures', 'Columbia ...",149.478,1131450163,['United States of America'],...,02 Jul 2019,129 min,Jon Watts,"Tom Holland, Samuel L. Jackson, Jake Gyllenhaa...","Italian, Czech, English",USA,"[{'Source': 'Internet Movie Database', 'Value'...",69.0,7.7,"187,214"

In [4]:
df_imdb.to_csv("output_data/imdb_api_movie_2019.csv",index=False)

#### Clean Up Final Data Frame

In [5]:
#Get the column names to drop repeat columns
df_imdb.columns

Index(['ID', 'Title', 'Adult', 'Budget', 'Genres', 'Language',
       'Production Company', 'Popularity', 'Revenue', 'Production Country',
       'Release Date', 'Run Time', 'Vote Average', 'Vote Count', 'imdb_id',
       'omdb_id', 'omdb_title', 'omdb_year', 'omdb_rated', 'omdb_released',
       'omdb_runtime', 'omdb_director', 'omdb_actors', 'omdb_language',
       'omdb_country', 'omdb_ratings', 'omdb_metascore', 'omdb_imdbRating',
       'omdb_imdbVotes'],
      dtype='object')

In [5]:
df_movie=df_imdb.drop(columns=["ID",
                               "Release Date",
                               "omdb_released",
                               "Language",
                               "Genres",
                               "omdb_runtime",
                               "imdb_id",
                               "omdb_id",
                               "omdb_title",
                               "omdb_year",
                               "omdb_country",
                               "omdb_ratings"])
df_movie.head()

,Title,Adult,Budget,Production Company,Popularity,Revenue,Production Country,Run Time,Vote Average,Vote Count,...,Genre5,Genre6,Genre7,omdb_rated,omdb_director,omdb_actors,omdb_language,omdb_metascore,omdb_imdbRating,omdb_imdbVotes
0,Joker,False,55000000,"['DC Entertainment', 'Warner Bros. Pictures', ...",601.364,788300000,['United States of America'],122.0,8.6,4118,...,NaN,NaN,NaN,R,Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",English,59.0,8.9,"360,218"
1,Maleficent: Mistress of Evil,False,0,['Walt Disney Pictures'],257.685,0,['United States of America'],118.0,7.2,395,...,NaN,NaN,NaN,PG,Joachim Rønning,"Angelina Jolie, Elle Fanning, Imelda Staunton,...",English,NaN,NaN,NaN
2,Terminator: Dark Fate,False,160000000,"['Lightstorm Entertainment', 'Skydance Media',...",223.592,0,"['China', 'United States of America']",128.0,6.8,61,...,NaN,NaN,NaN,NaN,Tim Miller,"Linda Hamilton, Arnold Schwarzenegger, Mackenz...",English,NaN,NaN,NaN
3,The Lion King,False,260000000,"['Walt Disney Pictures', 'Fairview Entertainme...",180.573,1649676757,['United States of America'],118.0,7.1,3183,...,NaN,NaN,NaN,PG,Jon Favreau,"Chiwetel Ejiofor, John Oliver, James Earl Jone...",English,55.0,7.1,"102,621"
4,Spider-Man: Far from Home,False,160000000,"['Marvel Studios', 'Sony Pictures', 'Columbia ...",149.478,1131450163,['United States of America'],129.0,7.6,4656,...,NaN,NaN,NaN,PG-13,Jon Watts,"Tom Holland, Samuel L. Jackson, Jake Gyllenhaa...","Italian, Czech, English",69.0,7.7,"187,214"

In [9]:
df_movie.rename(columns={"omdb_rated":"Rated",
                         "omdb_director":"Director",
                         "omdb_actors":"Actors",
                         "omdb_language":"Language",
                         "omdb_metascore":"Metascore",
                         "omdb_imdbRating":"IMDB Rating",
                         "omdb_imdbVotes":"IMDB Votes"})
df_movie.head(1)

,Title,Adult,Budget,Production Company,Popularity,Revenue,Production Country,Run Time,Vote Average,Vote Count,...,Genre5,Genre6,Genre7,omdb_rated,omdb_director,omdb_actors,omdb_language,omdb_metascore,omdb_imdbRating,omdb_imdbVotes
0,Joker,False,55000000.0,"['DC Entertainment', 'Warner Bros. Pictures', ...",601.364,788300000.0,['United States of America'],122.0,8.6,4118,...,NaN,NaN,NaN,R,Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",English,59.0,8.9,"360,218"

In [10]:
#Convert 0 value in Budget and Revenue to NaN since 0 means missing data here
df_movie["Budget"] = df_movie["Budget"].replace(0,np.nan)
df_movie["Revenue"] = df_movie["Revenue"].replace(0,np.nan)
df_movie.head()

,Title,Adult,Budget,Production Company,Popularity,Revenue,Production Country,Run Time,Vote Average,Vote Count,...,Genre5,Genre6,Genre7,omdb_rated,omdb_director,omdb_actors,omdb_language,omdb_metascore,omdb_imdbRating,omdb_imdbVotes
0,Joker,False,55000000.0,"['DC Entertainment', 'Warner Bros. Pictures', ...",601.364,7.883000e+08,['United States of America'],122.0,8.6,4118,...,NaN,NaN,NaN,R,Todd Phillips,"Joaquin Phoenix, Robert De Niro, Zazie Beetz, ...",English,59.0,8.9,"360,218"
1,Maleficent: Mistress of Evil,False,NaN,['Walt Disney Pictures'],257.685,NaN,['United States of America'],118.0,7.2,395,...,NaN,NaN,NaN,PG,Joachim Rønning,"Angelina Jolie, Elle Fanning, Imelda Staunton,...",English,NaN,NaN,NaN
2,Terminator: Dark Fate,False,160000000.0,"['Lightstorm Entertainment', 'Skydance Media',...",223.592,NaN,"['China', 'United States of America']",128.0,6.8,61,...,NaN,NaN,NaN,NaN,Tim Miller,"Linda Hamilton, Arnold Schwarzenegger, Mackenz...",English,NaN,NaN,NaN
3,The Lion King,False,260000000.0,"['Walt Disney Pictures', 'Fairview Entertainme...",180.573,1.649677e+09,['United States of America'],118.0,7.1,3183,...,NaN,NaN,NaN,PG,Jon Favreau,"Chiwetel Ejiofor, John Oliver, James Earl Jone...",English,55.0,7.1,"102,621"
4,Spider-Man: Far from Home,False,160000000.0,"['Marvel Studios', 'Sony Pictures', 'Columbia ...",149.478,1.131450e+09,['United States of America'],129.0,7.6,4656,...,NaN,NaN,NaN,PG-13,Jon Watts,"Tom Holland, Samuel L. Jackson, Jake Gyllenhaa...","Italian, Czech, English",69.0,7.7,"187,214"

#### Cleaning Result Summary

In [11]:
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9997 entries, 0 to 9996
Data columns (total 24 columns):
Title                 9997 non-null object
Adult                 9997 non-null bool
Budget                3231 non-null float64
Production Company    9997 non-null object
Popularity            9997 non-null float64
Revenue               2943 non-null float64
Production Country    9997 non-null object
Run Time              9653 non-null float64
Vote Average          9997 non-null float64
Vote Count            9997 non-null int64
Genre1                9869 non-null object
Genre2                7015 non-null object
Genre3                3671 non-null object
Genre4                1211 non-null object
Genre5                279 non-null object
Genre6                56 non-null object
Genre7                8 non-null object
omdb_rated            7491 non-null object
omdb_director         9680 non-null object
omdb_actors           9675 non-null object
omdb_language         9590 non-null object
omdb_metascore        4561 non-null float64
omdb_imdbRating       9557 non-null float64
omdb_imdbVotes        9557 non-null object
dtypes: bool(1), float64(7), int64(1), object(15)
memory usage: 1.8+ MB

In [12]:
df_movie.to_csv("output_data/cleanup_movie_2019.csv",index=False)